openapi: 3.1.0
info:
  title: Gatekeeper API
  version: 1.0.0
paths:
  /openapi:
    get:
      summary: Returns this document as JSON.
      responses:
        "200":
          description: This document.
          content:
            application/json:
              schema:
                type: object
